name: devScripts
on:
  workflow_dispatch:
  schedule:
    - cron: '00 8 * * 1'

jobs:
  update:
    uses: salesforcecli/github-workflows/.github/workflows/devScriptsUpdate.yml@main
    secrets:
      SVC_CLI_BOT_GITHUB_TOKEN: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
